### PR TITLE
Rf updates

### PR DESCRIPTION
**Pull request by ryanfranz**
Changes from Jerome's review

### CODE REVIEW

**Review by cnreediii — APPROVED** [review]

**Comment by DavidFLOR** [comment]
Ryan, I'm not sure how we got here, but there are five "conflicts" between 11-tiling-coverages.adoc in your branch and the Master branch.  Some of them are easy for me to see, and I started resolving them by always choosing the version in your branch.  But when I reached the fourth marked conflict I started to get uneasy.

May I ask you please to resolve the five conflicts in 11-tiling-coverages.adoc, and then I will approve the pull request and do the merge?

You can ignore index.html; it changes everytime anyone anywhere makes a commit to Master

**Comment by jerstlouis** [comment]
@DavidFLOR , when Carl merged in my pull request, that should have brought in all of the changes from @ryanfranz , as they were all in the commits history.
I think you just want to close this pull request, any attempt to "merge" it will just break / undo later work.

**Comment by cnreediii** [comment]
What Jerome said :-)

**Comment by cnreediii** [comment]
Jerome used this branch for his content. No need to merge back into master

**Comment by ryanfranz** [comment]
Ok, so is everything good here on the merge?  Thanks for the hard work!

**Comment by DavidFLOR** [comment]
Everything is OK, thanks Ryan; false alarm.  I lost the bubble.

**Pull request closed without merging**
